moveit/moveit_calibration

moveit_calibration_plugins/handeye_calibration_solver/src/handeye_solver_default.cpp
Some functions (PyInt_AsLong and PyString_FromString) used in Python 2 are deprecated in Python 3. This changes are needed if you would like to build your project with Python3 support.
=> Added support for Python 3

moveit_calibration_plugins/package.xml
Missing dependency on `libjsoncpp-dev` added to `moveit_calibration_plugins/package.xml`. I ran into this while doing a fresh install in a Docker container.
=> Add missing jsoncpp dependency

moveit_calibration_gui/handeye_calibration_rviz_plugin/include/moveit/handeye_calibration_rviz_plugin/handeye_control_widget.h, moveit_calibration_gui/handeye_calibration_rviz_plugin/src/handeye_control_widget.cpp
This provides a way to save the samples for debugging the solver. #30 #28 
This commit adds a "Save Samples" button to the Calibrate tab. Clicking it opens a file chooser dialog, and going through it saves the collected samples in a yaml file.
The format is simple -- a list of row-major 4x4 transform matrices. Sample output is attached.
```yaml
- 
effector_wrt_world:
- 0.764688963748736
- -0.6442974911606826
- 0.01146872289901995
- 0.4005766133871394
- -0.644099015765711
- -0.763667760969267
- 0.04413625205914794
- -0.05287948882914778
- -0.01967858253347301
- -0.04113749798221127
- -0.9989596887008187
- 0.4567383838863587
- 0
- 0
- 0
- 1
object_wrt_sensor:
- -0.181991113173958
- 0.2090995110627794
- -0.9608104417304987
- 1.021420952922779
- 0.05426406433777489
- -0.973503588627963
- …
```
=> button for saving samples for debugging

moveit_calibration_gui/handeye_calibration_rviz_plugin/include/moveit/handeye_calibration_rviz_plugin/handeye_context_widget.h
Since this package is not yet released in Noetic, we had to build it from the source in catkin_ws.
The only error that occured was:`handeye_calibration_rviz_plugin/handeye_context_widget.h:244:30: error: field ‘tf_listener_’ has incomplete type ‘tf2_ros::TransformListener’`
This PR fixes it.
Dependencies `baldor`, `handeye` and `moveit_visual_tools` are also not released in Noetic, but they build successfully in the Noetic environment.
=> Add missing include so that package builds in Noetic

moveit_calibration_gui/handeye_calibration_rviz_plugin/src/handeye_control_widget.cpp, moveit_calibration_gui/handeye_calibration_rviz_plugin/src/handeye_target_widget.cpp
Sometimes on some systems, the dialog to choose a file to load or save doesn't appear. After some searching, I found this change as a fix/workaround.
=> added DontUseNativeDialog option to QFileDialogs

moveit_calibration_gui/handeye_calibration_rviz_plugin/src/handeye_control_widget.cpp
When writing the calibration launch file, specify the rotation with a quaternion instead of Euler angles.
*Edited to add:* I decided to output the Euler angles also, in a comment, so that they can be copy/pasted into a URDF.
=> output quaternion instead of euler angles

moveit_calibration_plugins/CMakeLists.txt
Using `colcon` as build system fails with linking errors `undefined reference to cv::imread`.
This PR adds `imgcodecs` to the required OpenCV libs to fix this issue.
=> add 'imgcodecs' to required OpenCV libs for 'cv::imread'

moveit_calibration_gui/handeye_calibration_rviz_plugin/src/handeye_control_widget.cpp
Thanks to @FrankLin9981 for finding this in #54. This change fixes the UI issue where you have to click "Execute" to move the arm and then click it again to take a sample.
=> Fix execute success issue

moveit_calibration_plugins/CMakeLists.txt
As reported in issue #9 trying to load the calibration plugin in Rviz after building it I get the following error:
```
The class required for this panel, 'moveit_rviz_plugin/HandEyeCalibration', could not be loaded.
Error:
Failed to load library /root/underlay_ws/devel/lib/libmoveit_handeye_calibration_rviz_plugin.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libmoveit_planning_scene_monitor.so.1.0.4: cannot open shared object file: No such file or directory)
```
After some search I found [here](http://wiki.ros.org/class_loader) that: _pluginlib as of version 1.9 and class_loader HIGHLY discourage linking applications directly …
=> fix: Remove directly link of plugin libraries

moveit_calibration_gui/handeye_calibration_rviz_plugin/src/handeye_control_widget.cpp
I hit a solver failure because the camera orientation quaternion reported here was 1e-8 short. Renormalizing fixed it.
=> Renormalize transforms when captured

.github/workflows/industrial_ci_action.yml
industrial_ci has explicit method for specifying underlay built into docker image.  Using that instead of BEFORE_ hook.
=> Use UNDERLAY feature of industrial_ci

.github/workflows/industrial_ci_action.yml
Reverts ros-planning/moveit_calibration#76. Locally, when I run `rosrun industrial_ci rerun_ci` with the `UNDERLAY` argument, it fails to find catkin when building the upstream workspace. Switching back to the old way fixes it.
=> Revert "Use UNDERLAY feature of industrial_ci"

moveit_calibration_plugins/CMakeLists.txt
Added suggested warning about OpenCV 3.2:
```
Warnings   << moveit_calibration_plugins:cmake /home/john/ws_handeye/logs/moveit_calibration_plugins/build.cmake.000.log
CMake Warning at /home/john/ws_handeye/src/moveit_calibration/moveit_calibration_plugins/CMakeLists.txt:25 (message):
Your version of OpenCV (3.2) is known to have buggy ArUco pose detection!
Use a ChArUco target or upgrade OpenCV
```
=> Added cmake warning about OpenCV 3.2

moveit_calibration_gui/handeye_calibration_rviz_plugin/src/handeye_control_widget.cpp
Updated control tab layout:
The load and save buttons in the "Settings" group were previously all stacked vertically. This moves them into two columns with each load and save in a row, for more efficient use of space. I also increased the minimum vertical size to the size in the screenshot (any smaller and the buttons start to shrink).
=> Rearrange control tab

moveit_calibration_gui/handeye_calibration_rviz_plugin/src/handeye_control_widget.cpp, moveit_calibration_plugins/handeye_calibration_solver/include/moveit/handeye_calibration_solver/handeye_solver_base.h, moveit_calibration_plugins/handeye_calibration_solver/include/moveit/handeye_calibration_solver/handeye_solver_default.h, moveit_calibration_plugins/handeye_calibration_solver/src/handeye_solver_default.cpp, moveit_calibration_plugins/handeye_calibration_solver/test/handeye_solver_test.cpp
Now `solve()` will output a helpful error message, and the GUI will display this in the dialog that pops up. Fixes #64 .
=> Display more informative error message when solve() fails

moveit_calibration_gui/handeye_calibration_rviz_plugin/include/moveit/handeye_calibration_rviz_plugin/handeye_target_widget.h, moveit_calibration_gui/handeye_calibration_rviz_plugin/src/handeye_target_widget.cpp, moveit_calibration_plugins/handeye_calibration_target/include/moveit/handeye_calibration_target/handeye_target_base.h
Fix for a bug I just ran into. If the camera intrinsics were already received, and then you change the target type (ArUco/ChArUco), the new target wouldn't receive the correct intrinsics. The target object is created with default intrinsics (identity camera matrix and all zero distortion), and then the target tab wouldn't send its cached intrinsics to the target object, since they match the incoming CameraInfo message. This PR just sends the intrinsics after the new target object is created.
I also made some more stylistic changes to `cameraInfoCallback`.
=> fix missing intrinsics on target type change

.github/workflows/ci.yaml, melodic_upstream.rosinstall, upstream.rosinstall
Source build of MoveIt (and rviz_visual_tools) is not necessary on Noetic (fixes #71).
~~This change will break the Melodic build, so maybe it's time to have separate devel branches. What would be the preferred approach at this point?~~ Actually, it works for both. I just had to learn a bit more about industrial_ci.
=> Source build of MoveIt is unneeded

moveit_calibration_gui/handeye_calibration_rviz_plugin/include/moveit/handeye_calibration_rviz_plugin/handeye_control_widget.h, moveit_calibration_gui/handeye_calibration_rviz_plugin/src/handeye_control_widget.cpp, moveit_calibration_plugins/handeye_calibration_solver/include/moveit/handeye_calibration_solver/handeye_solver_base.h, moveit_calibration_plugins/handeye_calibration_solver/src/handeye_solver_default.cpp
This adds a function to the solver plugin to calculate the reprojection error. It also displays the error in the calibration tab, beneath the samples.
=> Calculate and report reprojection error

moveit_calibration_gui/handeye_calibration_rviz_plugin/CMakeLists.txt, moveit_calibration_gui/handeye_calibration_rviz_plugin/include/moveit/handeye_calibration_rviz_plugin/handeye_calibration_display.h, moveit_calibration_gui/handeye_calibration_rviz_plugin/include/moveit/handeye_calibration_rviz_plugin/handeye_calibration_frame.h, moveit_calibration_gui/handeye_calibration_rviz_plugin/include/moveit/handeye_calibration_rviz_plugin/handeye_context_widget.h, moveit_calibration_gui/handeye_calibration_rviz_plugin/include/moveit/handeye_calibration_rviz_plugin/handeye_control_widget.h, moveit_calibration_gui/handeye_calibration_rviz_plugin/include/moveit/handeye_calibration_rviz_plugin/handeye_target_widget.h, moveit_calibration_gui/handeye_calibration_rviz_plugin/src/handeye_calibration_display.cpp, moveit_calibration_gui/handeye_calibration_rviz_plugin/src/handeye_calibration_frame.cpp, moveit_calibration_gui/handeye_calibration_rviz_plugin/src/handeye_context_widget.cpp, moveit_calibration_gui/handeye_calibration_rviz_plugin/src/handeye_control_widget.cpp, moveit_calibration_gui/handeye_calibration_rviz_plugin/src/handeye_target_widget.cpp, moveit_calibration_gui/handeye_calibration_rviz_plugin/src/plugin_init.cpp, moveit_calibration_gui/handeye_calibration_rviz_plugin_description.xml, moveit_calibration_plugins/handeye_calibration_target/include/moveit/handeye_calibration_target/handeye_target_base.h
Convert the RViz plugin from an rviz::Panel object to an rviz::Display. This allows parameter input and status feedback in the "Displays" panel.
While I was at it, I added parameters for the move_group namespace and PSM topic (borrowed from the PlanningScene display plugin), as well as some status messages for various components.
=> Convert panel to rviz display

.pre-commit-config.yaml
Running pre-commit with the current black version is broken, and should be updated as per https://github.com/ros-planning/moveit2/pull/1148
=> Update black version

.github/workflows/ci.yaml, .github/workflows/format.yaml, moveit_calibration_gui/CMakeLists.txt, moveit_calibration_plugins/CMakeLists.txt, moveit_calibration_plugins/package.xml
- Replace enforcement of (old) C++14 standard with moveit_build_options()
Ubuntu 22.04 uses C++17 as default and fails on old C++14
- Modernize CI setup
=> [ROS-O] Modernize CI / cmake
